### ISSUE TITLE
Provide with handler support

### ISSUE THREAD

**Issue by DreamFlasher** [python-lz4/python-lz4#17] opened 2017-02-28 10:41 UTC
Support read and write via with file handler as gzip.open and BZ2File do. Eg.:

`with lz4.open(filename, 'wb') as f:`

**Comment by jonathanunderwood** [comment] 2017-03-05 09:59
Good suggestion. Will think about the implementation of that after I cut the 0.9 release.

**Comment by jonathanunderwood** [comment] 2017-03-18 15:06
Som the beginnings of this are present in the lz4.frame module, though that's still a work in progress. 

Were you asking for it for the lz4.block module?

**Comment by DreamFlasher** [comment] 2017-03-19 12:06
I don't care about whether it's implemented for frame or block, I am just looking for a faster option than gzip, which provides me the same interface. Reading line by line in a streamed manner is what I'd like to be able to do :)

**Comment by Ponyboy47** [comment] 2017-12-05 17:54
Out of curiosity, has any progress been made on this?

At my job, I have been tasked with adding the capability to write to files in various compressed formats. We're using gzip, and lzma (and we're debating bzip2 as well), but it's all configurable and so I'm using the stream reading/writing features to make it easy to switch between formats. We would like to be able to use lz4 as well since other parts of our system are using lz4 (and it's fast), but because the python libraries are all lacking this functionality we can't do it yet.

I would be happy to help with this since I need it anyways :)

**Comment by jonathanunderwood** [comment] 2017-12-05 18:17
Some progress in the decompress_rework branch, but file handling support isn't there yet. Would be trivial to add though :)

**Comment by jonathanunderwood** [comment] 2017-12-24 14:24
This should be the basis of the work:

https://github.com/python/cpython/blob/master/Lib/gzip.py

**Comment by jonathanunderwood** [comment] 2018-01-06 14:16
Work has started on the `file_handler` branch. It's scrappy at the moment. Writing a file works. Reading a file doesn't. Much left to do, but it's a start.

**Comment by jonathanunderwood** [comment] 2018-01-14 13:28
More WIP with a working file read/decompress sketch. the lz4.frame.decompress_chunk API needed enhancing for this. Lots of broken tests as a result, but it's heading in the right direction. Code and git history will need cleanups and further work yet though.

**Comment by jonathanunderwood** [comment] 2018-01-21 00:59
The `file_handler` branch is just about done. Just need to update documentation, and add a few more tests, and it'll be good to go. I'd REALLY welcome some testing at this point.

**Comment by jonathanunderwood** [comment] 2018-01-21 12:28
I have just cut release v0.19.0 which adds in file handling capability. I'll close this issue, but please open new tickets if you find any problems (preferably with a reproducer).

**Closed by jonathanunderwood** 2018-01-21 12:28 UTC
Labels: WIP, enhancement
