### ISSUE TITLE
testing takes abnormally long with python 3.6, but is reasonable with 2.7

### ISSUE THREAD

**Issue by frispete** [python-lz4/python-lz4#147] opened 2018-08-07 19:57 UTC
Hi,

in an attempt to package lz4 for the openSUSE project, we see very differing testing times between python 2.7 and 3.6 builds.

Here's an example: 
```
[  105s] ============================= test session starts ==============================
[  105s] platform linux2 -- Python 2.7.15, pytest-3.6.3, py-1.5.3, pluggy-0.6.0
[  105s] rootdir: /home/abuild/rpmbuild/BUILD/lz4-2.0.2, inifile: setup.cfg
[  114s] collected 18893 items
[...] 
[  405s] ================== 18889 passed, 4 skipped in 300.56 seconds ===================

[  410s] ============================= test session starts ==============================
[  410s] platform linux -- Python 3.6.5, pytest-3.6.3, py-1.5.3, pluggy-0.6.0
[  410s] rootdir: /home/abuild/rpmbuild/BUILD/lz4-2.0.2, inifile: setup.cfg
[  418s] collected 18893 items
[...]
[ 9610s] ======================= 18893 passed in 9200.23 seconds ========================
```
Sure, we have quicker hosts in the build cluster, but 5 minutes versus 2 and a half hours is an abnormal deviation. It might be due to the 4 skipped tests, but having builds taking this long **is** painful. Of course, you can argue, that testing isn't necessary, but we're building for a varying number of different interpreters and real world distributions, where having tested all the builds is a good thing (tm). 

**Is that observed timing behaviour to be expected?**

For reference, here's the [build log](https://build.opensuse.org/package/live_build_log/devel:languages:python/python-lz4/openSUSE_Tumbleweed/x86_64), use the `Download logfile` link for a full build log.

**Comment by jonathanunderwood** [comment] 2018-08-07 20:12
That's something very specific to the OpenSUSE build service, then. For reference, here's the last release building and testing on Travis:

https://travis-ci.org/python-lz4/python-lz4/builds/410281443?utm_source=github_status&utm_medium=notification

Sure, there's some differences in total time taken, but nothing on the scale you see. Similarly, I don't see the problem you describe on the Fedora build service when I build the packages there, either.

The problem seems to be in the test_frame_4.py tests, towards the end. Those tests use data generated using `os.urandom()`. I am guessing here, but perhaps the build host/container is running out of entropy for the rng?

**Comment by frispete** [comment] 2018-08-07 21:34
Thanks for the ultra quick reply, Jonathan, much appreciated. 
Does the Travis builds use the native lz4 lib, or do they use the bundled lib?

BTW, I'm observing this behaviour for local builds as well (with a pretty current kernel, FWIW).

Will investigate further...

**Comment by jonathanunderwood** [comment] 2018-08-07 22:03
> Does the Travis builds use the native lz4 lib, or do they use the bundled lib?

Travis builds will be using the bundled lib. The Fedora build uses system lib. I presume your build is using a system lib? Which version?

**Comment by jonathanunderwood** [comment] 2018-08-08 13:06
If you can reproduce locally, that's a good opportunity for nailing this down. Here's what I suggest: creating a virtual environment (`python3 -m venv venv` or similar), installing the lz4 package from source (`pip install -e .` from the root of an unzipped tarball), and then running `pytest --durations=0 tests/frame/test_frame_4.py`. That will print out execution times of all tests along with the args of each test.

**Comment by frispete** [comment] 2018-08-08 17:28
Dear Jonathan, thanks for your persistent support here! 

> Travis builds will be using the bundled lib. The Fedora build uses system lib. I presume your build is using a system lib? Which version?

I've tested both lib variants, bundled and system, without difference, but they're both 1.8.2 anyway. 

These tests are all done for target Tumbleweed, which usually is quite current, using the lz4 system lib. My local system is a highly customized openSUSE derivative, with kernel 4.17.12, python 2.7.15 and 3.6.5. Pretty current as well (apart from glibc).

Following your procedure, I cannot reproduce this issue:
```
[   28s] ============================ slowest test durations ============================
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-False-True-True-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-False-True-False-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-True-True-False-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-True-False-True-False-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-True-False-True-False-False]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-False-True-True-False]
```
nor with running the full test (just omitting the testfile argument):
```
================================================ slowest test durations ================================================
34.95s call     tests/frame/test_frame_5.py::test_frame_decompress_chunk_mem_usage[data0]
6.97s call     tests/frame/test_frame_5.py::test_frame_open_decompress_mem_usage[data0]
5.67s call     tests/frame/test_frame_5.py::test_frame_decompress_mem_usage[data0]
3.54s call     tests/frame/test_frame_3.py::test_decompress_truncated[data0]
1.37s call     tests/block/test_block_2.py::test_huge
0.26s call     tests/block/test_block_3.py::test_block_decompress_mem_usage[data0]
0.09s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data1-1-7-True-False-True-False-False]
```
If I run test_frame_4.py in a packaging chroot, things still behave consistently:
```
[   28s] ============================ slowest test durations ============================
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-False-True-True-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-False-True-False-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-True-True-False-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-True-False-True-False-True]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-True-False-True-False-False]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-False-True-True-False]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-True-False-False-False]
[   28s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-True-False-False-False-False]
```
but it behaves quite differently running the full test in the build chroot:
```
[ 2960s] 2809.03s call     tests/frame/test_frame_5.py::test_frame_decompress_chunk_mem_usage[data0]
[ 2960s] 21.71s call     tests/frame/test_frame_3.py::test_decompress_truncated[data0]
[ 2960s] 9.22s call     tests/frame/test_frame_5.py::test_frame_decompress_mem_usage[data0]
[ 2960s] 7.33s call     tests/frame/test_frame_5.py::test_frame_open_decompress_mem_usage[data0]
[ 2960s] 1.36s call     tests/block/test_block_2.py::test_huge
[ 2960s] 0.80s call     tests/block/test_block_3.py::test_block_decompress_mem_usage[data0]
[ 2960s] 0.45s call     tests/frame/test_frame_7.py::test_roundtrip_multiframe_2[data0]
[ 2960s] 0.24s call     tests/frame/test_frame_7.py::test_roundtrip_multiframe_4[data0]
[ 2960s] 0.24s call     tests/frame/test_frame_7.py::test_roundtrip_multiframe_3[data0]
[ 2960s] 0.09s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-True-False-False-False-False]
```
Yes, approaching an hour again.

Now, I've isolated test_frame_4.py and test_frame_5.py:
```
[    4s] tests/frame/test_frame_4.py ............................................ [  1%]
[    4s] ........................................................................ [  4%]
[    4s] ........................................................................ [  7%]
[    4s] ........................................................................ [ 10%]
[    5s] ........................................................................ [ 12%]
[    5s] ........................................................................ [ 15%]
[    5s] ........................................................................ [ 18%]
[    6s] ........................................................................ [ 21%]
[    7s] ........................................................................ [ 24%]
[    7s] ........................................................................ [ 26%]
[    8s] ........................................................................ [ 29%]
[    8s] ........................................................................ [ 32%]
[    9s] ........................................................................ [ 35%]
[    9s] ........................................................................ [ 38%]
[   10s] ........................................................................ [ 41%]
[   11s] ........................................................................ [ 43%]
[   12s] ........................................................................ [ 46%]
[   13s] ........................................................................ [ 49%]
[   13s] ........................................................................ [ 52%]
[   14s] ........................................................................ [ 55%]
[   14s] ........................................................................ [ 57%]
[   14s] ........................................................................ [ 60%]
[   15s] ........................................................................ [ 63%]
[   15s] ........................................................................ [ 66%]
[   16s] ........................................................................ [ 69%]
[   16s] ........................................................................ [ 71%]
[   17s] ........................................................................ [ 74%]
[   17s] ........................................................................ [ 77%]
[   18s] ........................................................................ [ 80%]
[   19s] ........................................................................ [ 83%]
[   21s] ........................................................................ [ 85%]
[   22s] ........................................................................ [ 88%]
[   24s] ........................................................................ [ 91%]
[   25s] ........................................................................ [ 94%]
[   26s] ........................................................................ [ 97%]
[   27s] ....................................................................     [ 99%]
[   56s] tests/frame/test_frame_5.py ....                                         [100%]
[   56s] 
[   56s] ============================ slowest test durations ============================
[   56s] 25.41s call     tests/frame/test_frame_5.py::test_frame_decompress_chunk_mem_usage[data0]
[   56s] 1.87s call     tests/frame/test_frame_5.py::test_frame_open_decompress_mem_usage[data0]
[   56s] 0.85s call     tests/frame/test_frame_5.py::test_frame_decompress_mem_usage[data0]
[   56s] 0.08s call     tests/frame/test_frame_4.py::test_roundtrip_LZ4FrameCompressor_LZ4FrameDecompressor[data3-8-4-False-False-True-True-True]
```
Still fine. 

It only misbehaves, if all tests are executed in the build environment.

Since this is a chroot jail, it should have /dev/urandom available, and according to https://lwn.net/Articles/693189/, it shouldn't run out of entropy after being booted. I'm pretty sure that my system doesn't offer the getrandom() syscall, hence reading from /dev/urandom should result in a read() syscall.

But when stracing the process during the "no progress phase", it just allocates some ram with a couple of brk()s, move around these blocks with mmap() and mremap(), and dumping the mmaps with munmap. Then, it doesn't do any syscalls for ages (actually for 4-5 minutes), and repeats the pattern above.

The long periods of silence during that one core is kept busy imply, the cpu is spinning locally, obviously waiting for some (syscall-less) event.

Hrmpf. I'm running out of ideas right now.

**Comment by jonathanunderwood** [comment] 2018-08-08 17:38
OK, good work! That's eliminated anything to do with `urandom()` , then.

The big difference here is actually `python3 setup.py test` vs. `pytest ...`. The former will invoke pytest on all tests in the test suite, of which there are a very large number. PyTest can consume quite a lot of memory when there are a lot of tests to track. In fact, on automated AppVeyor builds I don't invoke `python3 setup.py test`, but rather execute pytest on each file separately - see the [tox.ini]( https://github.com/python-lz4/python-lz4/blob/master/tox.ini) file.

It would be interesting to know if you see the problem when running the tests via tox - any chance you could try that?

**Comment by frispete** [comment] 2018-08-09 17:16
Dear Jonathan,

just an update.

> The big difference here is actually python3 setup.py test vs. pytest .... The former will invoke pytest on all tests in the test suite, of which there are a very large number. PyTest can consume quite a lot of memory when there are a lot of tests to track.

It's definitely related to this, but I'm still not able to boil it down to some specific root cause.

> I wonder if there's an issue here with running out of memory, and swapping out - those 4-5 minutes of nothing could be paging stuff to disk?

Well, let's say, the test system is sufficiently equipped.. (i7-4790K, 32 GB RAM, 20 GB RAM available)

If I run the tests separately (pytest-$version), python2 is struggling in test_frame_4.py. 
If I run all tests at once (python-$version -m pytest), python2 behaves fine, but python3 is struggling in test_frame_4.py. 

Investigating straces wasn't that helpful as well but revealed, that my python3 does getrandom() syscalls (./Python/random.c, line 125):
```
#ifdef HAVE_GETRANDOM
        if (raise) {
            Py_BEGIN_ALLOW_THREADS
            n = getrandom(dest, n, flags);
            Py_END_ALLOW_THREADS
        }
        else {
            n = getrandom(dest, n, flags);
        }
#else
        /* On Linux, use the syscall() function because the GNU libc doesn't
           expose the Linux getrandom() syscall yet. See:
           https://sourceware.org/bugzilla/show_bug.cgi?id=17252 */
        if (raise) {
            Py_BEGIN_ALLOW_THREADS
            n = syscall(SYS_getrandom, dest, n, flags);
            Py_END_ALLOW_THREADS
        }
        else {
            n = syscall(SYS_getrandom, dest, n, flags);
        }
#endif
```
The last getrandom() syscall is done 51 secs after the build started. This definitely eliminates getrandom() as root cause now...

Here's the top 6 syscalls from stracing a python3 -m pytest --durations=0, sorted by delta-t:
```
0:04:36
  4426710: [  504s] 10:51:15 munmap(0x7fa0e238c000, 2383872) = 0

0:04:29
  4428027: [ 2310s] 11:21:21 munmap(0x7fa0dff44000, 2383872) = 0

0:04:28
  4426537: [  235s] 10:46:46 brk(0x55b5d964f000)            = 0x55b5d964f000

0:03:42
  4427538: [ 1649s] 11:10:20 munmap(0x7fa0e0149000, 2383872) = 0

0:03:39
  4427373: [ 1429s] 11:06:40 munmap(0x7fa0dfadf000, 2383872) = 0

  4427702: [ 1872s] 11:14:03 munmap(0x7fa0dff03000, 2383872) = 0

0:03:38
  4427042: [  992s] 10:59:24 munmap(0x7fa0dfadf000, 2383872) = 0

  4427208: [ 1210s] 11:03:01 munmap(0x7fa0e0149000, 2383872) = 0

0:03:37
  4427865: [ 2092s] 11:17:43 munmap(0x7fa0e0695000, 2383872) = 0

0:03:32
  4426877: [  780s] 10:55:51 munmap(0x7fa0dff44000, 2383872) = 0
```
left most column is a timedelta value [HH:MM:SS], then lnnr: build-log lines.
Yes, these syscalls take up to 4 and a half minute. 

I saw, that you fiddled with the allocators already in your tox.ini, but don't know, if/how that's helpful here. 

Last, but not least, I couldn't get tox to cooperate, will have to try harder...
This is all very time consuming, so please bear with me.

**Comment by jonathanunderwood** [comment] 2018-08-17 18:14
Hi @frispete, how're you getting on with this? I haven't managed to reproduce it locally, unfortunately.

**Comment by jonathanunderwood** [comment] 2018-10-13 11:44
I haven't been able to reproduce this issue. I'll close this issue, but please feel free to re-open it if you're able to provide any more information.

**Closed by jonathanunderwood** 2018-10-13 11:44 UTC
Labels: information needed
