### ISSUE TITLE
Error code: 11

### ISSUE THREAD

**Issue by Anabiotik** [python-lz4/python-lz4#176] opened 2019-08-08 21:52 UTC
I have this code on my local server

```
#!c:\Python27\python.exe
# -*- coding: utf-8 -*-
import cgi
import os
import struct
import zlib

from lz4.block import decompress

form = cgi.FieldStorage()
folder = form.getfirst("time")
name = form.getfirst("filename")

FOOTER_STRUCTURE = '4I4s'
FOOTER_SIZE = struct.calcsize(FOOTER_STRUCTURE)

infile = ".\\uploads\\" + folder + "\\" + name;
outPath = ".\\uploads\\" + folder + "\\";

with open(infile, 'rb') as f, open(outPath + name[:-5] , 'wb') as out:
    f.seek(-FOOTER_SIZE, os.SEEK_END)
    unpacked, packed, crc, ptype, marker = struct.unpack(FOOTER_STRUCTURE, f.read(FOOTER_SIZE))
    f.seek(0)
    result = decompress(f.read(packed), uncompressed_size=unpacked)
    out.write(result)
    out.close()
    f.close()


print("Content-Type: text/html; charset: utf-8\n\n")
```

After converting the file I need, I get a void and this error

```
I File "dvpl_unpack.py", line 22, in <module> 
result = decompress(f.read(packed), uncompressed_size=unpacked) 
_block.LZ4BlockError: Decompression failed: corrupt input or insufficient space 
in destination buffer. Error code: 11 
```

How to fix this error, preferably in a couple of lines))
Please pay attention

**Comment by jonathanunderwood** [comment] 2019-08-11 16:13
It's impossible to tell what the problem is from the information provided, as I can't see how the data has actually been compressed.

If I had to guess, I'd say that you're passing in an incorrect `uncompressed_size` value, or you're not passing in the right piece of the data. But honestly, without more information, it's impossible to say. 

However, this is an error with your code, and not the python-lz4 library, so I'll close this. You're welcome to provide more information if you want to, and I'll try to help.

**Closed by jonathanunderwood** 2019-08-11 16:13 UTC
