### ISSUE TITLE
Windows build instructions

### ISSUE THREAD

**Issue by pyhedgehog** [python-lz4/python-lz4#55] opened 2017-11-30 14:21 UTC
I understand how to build package "manually", but I want to know where to put `lz4` and `py3c` so `pip install lz4` can find it.

**Comment by jonathanunderwood** [comment] 2017-11-30 14:26
I don't really understand the question - both py3c and lz4 are bundled with the package, so you shouldn't need to put them anywhere. What exactly are you trying to do?

[Aside: Eventually I plan to also publish wheels for the package - windows builds are already being built in Appveyor, I just haven't gotten around to retrieving them and pushing them to pypi - needs scripting somehow. Patches welcome].

**Comment by pyhedgehog** [comment] 2017-12-01 12:08
I mean that `pip install lz4` fails with `Cannot open include file: 'lz4.h': No such file or directory`.

```console
C:\>py -3.7 -m pip install lz4
Collecting lz4
  Using cached lz4-0.11.1.tar.gz
Installing collected packages: lz4
  Running setup.py install for lz4 ... error
    Complete output from command C:\tools\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip-build-rrxocroa\\lz4\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\User\AppData\Local\Temp\pip-hqrr28on-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\lz4
    copying lz4\deprecated.py -> build\lib.win-amd64-3.7\lz4
    copying lz4\lz4version.py -> build\lib.win-amd64-3.7\lz4
    copying lz4\version.py -> build\lib.win-amd64-3.7\lz4
    copying lz4\__init__.py -> build\lib.win-amd64-3.7\lz4
    creating build\lib.win-amd64-3.7\lz4\block
    copying lz4\block\__init__.py -> build\lib.win-amd64-3.7\lz4\block
    creating build\lib.win-amd64-3.7\lz4\frame
    copying lz4\frame\__init__.py -> build\lib.win-amd64-3.7\lz4\frame
    running build_ext
    building 'lz4._version' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\lz4
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipy3c -IC:\tools\python37\include -IC:\tools\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tclz4/_version.c /Fobuild\temp.win-amd64-3.7\Release\lz4/_version.obj /Ot /Wall
    _version.c
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(49): warning C4820: '_finddata32i64_t': '4' bytes padding added after data member 'name'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(54): warning C4820: '_finddata64i32_t': '4' bytes padding added after data member 'attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(64): warning C4820: '__finddata64_t': '4' bytes padding added after data member 'attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(69): warning C4820: '__finddata64_t': '4' bytes padding added after data member 'name'
    C:\Program Files (x86)\Windows Kits\8.1\include\shared\basetsd.h(418): warning C4668: '_WIN32_WINNT' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(35): warning C4820: '_timespec64': '4' bytes padding added after data member 'tv_nsec'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(42): warning C4820: 'timespec': '4' bytes padding added after data member 'tv_nsec'
    c:\tools\python37\include\object.h(381): warning C4820: '_typeobject': '4' bytes padding added after data member 'tp_flags'
    c:\tools\python37\include\object.h(425): warning C4820: '_typeobject': '4' bytes padding added after data member 'tp_version_tag'
    c:\tools\python37\include\object.h(440): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'slot'
    c:\tools\python37\include\object.h(448): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'flags'
    c:\tools\python37\include\pytime.h(111): warning C4115: 'timeval': named type definition in parentheses
    c:\tools\python37\include\bytearrayobject.h(30): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'ob_exports'
    c:\tools\python37\include\bytesobject.h(41): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'ob_sval'
    c:\tools\python37\include\bytesobject.h(165): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'small_buffer'
    c:\tools\python37\include\unicodeobject.h(330): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'state'
    c:\tools\python37\include\unicodeobject.h(905): warning C4820: '<unnamed-tag>': '2' bytes padding added after data member 'readonly'
    c:\tools\python37\include\longintrepr.h(88): warning C4820: '_longobject': '4' bytes padding added after data member 'ob_digit'
    c:\tools\python37\include\memoryobject.h(45): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'flags'
    c:\tools\python37\include\memoryobject.h(62): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'flags'
    c:\tools\python37\include\methodobject.h(61): warning C4820: 'PyMethodDef': '4' bytes padding added after data member 'ml_flags'
    c:\tools\python37\include\moduleobject.h(62): warning C4820: 'PyModuleDef_Slot': '4' bytes padding added after data member 'slot'
    c:\tools\python37\include\pystate.h(85): warning C4820: '_is': '4' bytes padding added after data member 'config'
    c:\tools\python37\include\pystate.h(142): warning C4820: '_ts': '2' bytes padding added after data member 'recursion_critical'
    c:\tools\python37\include\pystate.h(162): warning C4820: '_ts': '4' bytes padding added after data member 'gilstate_counter'
    c:\tools\python37\include\pystate.h(197): warning C4820: '_ts': '4' bytes padding added after data member 'in_coroutine_wrapper'
    c:\tools\python37\include\genobject.h(32): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'gi_running'
    c:\tools\python37\include\genobject.h(52): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'cr_running'
    c:\tools\python37\include\genobject.h(68): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'ag_running'
    c:\tools\python37\include\descrobject.h(29): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'offset'
    c:\tools\python37\include\descrobject.h(33): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'flags'
    c:\tools\python37\include\structseq.h(20): warning C4820: 'PyStructSequence_Desc': '4' bytes padding added after data member 'n_in_sequence'
    c:\tools\python37\include\pyerrors.h(18): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\tools\python37\include\pyerrors.h(22): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\tools\python37\include\pyerrors.h(32): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\tools\python37\include\pyerrors.h(39): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\tools\python37\include\pyerrors.h(48): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\tools\python37\include\pyerrors.h(53): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\tools\python37\include\pyerrors.h(65): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\tools\python37\include\modsupport.h(90): warning C4820: '_PyArg_Parser': '4' bytes padding added after data member 'max'
    c:\tools\python37\include\pylifecycle.h(72): warning C4255: '_Py_CheckPython3': no function prototype given: converting '()' to '(void)'
    c:\tools\python37\include\import.h(141): warning C4820: '_frozen': '4' bytes padding added after data member 'size'
    c:\tools\python37\include\fileutils.h(25): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_dev'
    c:\tools\python37\include\fileutils.h(27): warning C4820: '_Py_stat_struct': '2' bytes padding added after data member 'st_mode'
    c:\tools\python37\include\fileutils.h(31): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_rdev'
    c:\tools\python37\include\fileutils.h(34): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_atime_nsec'
    c:\tools\python37\include\fileutils.h(36): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_mtime_nsec'
    lz4/_version.c(42): fatal error C1083: Cannot open include file: 'lz4.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\tools\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip-build-rrxocroa\\lz4\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\User\AppData\Local\Temp\pip-hqrr28on-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-build-rrxocroa\lz4\
```

**Comment by jonathanunderwood** [comment] 2017-12-01 14:15
OK, that looks like a bug with the logic in setup.py which endeavours to ensure that the bundled lz4 header files are in the include path if needed (i.e. if the lz4 libraries are not on the system). I'm slightly surprised that the Appveyor builds work, whereas yours doesn't. However the Appveyor builds don't currently include Python 3.7, so that may be a clue. Not sure, will look into it when I have a chance.

**Comment by pyhedgehog** [comment] 2017-12-01 18:53
It's same on 3.6.

**Comment by jonathanunderwood** [comment] 2017-12-20 17:42
Can you check out the branch`windows_build_debug` and try and build that? It will print out the build configuration so we can see what's wrong.

**Comment by jonathanunderwood** [comment] 2017-12-26 14:30
Windows wheels are now being published to PyPi on release.

I am still unable to reproduce this issue. I'll close it for now, but feel free to re-open it if you're able to provide any more information.

**Closed by jonathanunderwood** 2017-12-26 14:30 UTC
Labels: bug, information needed
