### ISSUE TITLE
LZ4FrameFile read() fails on windows

### ISSUE THREAD

**Issue by steve-talent** [python-lz4/python-lz4#172] opened 2019-05-08 21:18 UTC
Tested with Python 3.7.3, 3.6.x, and 3.5.x. Code works fine under linux but consistently fails under windows 10.

In this example, 'tprofFile' was compressed using lz4 frame format by another application.
#### Console log
A few `print()` statements were added to `__compression.py` to localize the issue.
This is console output from the code below.
```
$ py TimelineLogViewer/tprof2db.py RouterPerformanceTest tprofdump-192.168.1.26-2019-05-02_10_15_59.tprof.lz4
self.tprof <lz4.frame.LZ4FrameFile object at 0x00000214B1030320>
magicStruct.size 5
read size 8192
read self._decompressor.eof False
read BUFFER_SIZE 8192
read len(rawblock) 8192
read len(data) 0
read BUFFER_SIZE 8192
read len(rawblock) 8192
read len(data) 65536
len(byte_view 8192
len(data) 65536
Traceback (most recent call last):
  File "TimelineLogViewer/tprof2db.py", line 711, in <module>
    main()
  File "TimelineLogViewer/tprof2db.py", line 640, in main
    tprof = TprofFile( args.tprofFile, sqliteData )
  File "TimelineLogViewer/tprof2db.py", line 94, in __init__
    buffer = self.tprof.read( self.magicStruct.size ) # read version, depending on this we will know the header config
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\site-packages\lz4\frame\__init__.py", line 635, in read
    return self._buffer.read(size)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\_compression.py", line 71, in readinto
    byte_view[:len(data)] = data
ValueError: memoryview assignment: lvalue and rvalue have different structures
```
#### Calling code
This is the code that uses `lz4.frame.LZ4FrameFile`. The size of the input file is about 1GB.
```python
class TprofFile( object ):
    ''' class that knows how to parse a tprof timeline binary file '''

    def __init__( self, tprofFile, dbconn ):

        #self.tprof = open( tprofFile, 'rb' )
        self.tprof = lz4.frame.open( tprofFile, 'rb' )
        print( "self.tprof", self.tprof )

        self.magicStruct = struct.Struct( '<5s' )
        print( "magicStruct.size", self.magicStruct.size )
        buffer = self.tprof.read( self.magicStruct.size ) # read version, depending on this we will know the header config
```
#### Print statements added to `_compression.py`
The call to `self._decompressor.decompress(rawblock, size)` is returning 64KB but the requested size was 8KB.
```python
    def readinto(self, b):
        with memoryview(b) as view, view.cast("B") as byte_view:
            data = self.read(len(byte_view))
            print('readinto len(byte_view)',len(byte_view))
            print('readinto len(data)',len(data))
            byte_view[:len(data)] = data
        return len(data)

    def read(self, size=-1):
        print('read size',size)
        print('read self._decompressor.eof',self._decompressor.eof)
        if size < 0:
            return self.readall()

        if not size or self._eof:
            return b""
        data = None  # Default if EOF is encountered
        # Depending on the input data, our call to the decompressor may not
        # return any data. In this case, try again after reading another block.
        while True:
            if self._decompressor.eof:
                rawblock = (self._decompressor.unused_data or
                            self._fp.read(BUFFER_SIZE))
                if not rawblock:
                    break
                # Continue to next stream.
                self._decompressor = self._decomp_factory(
                    **self._decomp_args)
                print('self._decomp_args',self._decomp_args)
                try:
                    data = self._decompressor.decompress(rawblock, size)
                except self._trailing_error:
                    # Trailing data isn't a valid compressed stream; ignore it.
                    break
            else:
                if self._decompressor.needs_input:
                    print('read BUFFER_SIZE',BUFFER_SIZE)
                    rawblock = self._fp.read(BUFFER_SIZE)
                    print('read len(rawblock)',len(rawblock))
                    if not rawblock:
                        raise EOFError("Compressed file ended before the "
                                       "end-of-stream marker was reached")
                else:
                    rawblock = b""
                data = self._decompressor.decompress(rawblock, size)
                print('read len(data)',len(data))
            if data:
                break
        if not data:
            self._eof = True
            self._size = self._pos
            return b""
        self._pos += len(data)
        return data
```

**Comment by steve-talent** [comment] 2019-05-10 17:25
I added a few more debug prints and located a possible root cause. len(data) is 65536 but len(byte_view) is len(byte_view) is only 8192. The memoryview buffer is smaller than the data buffer returned by self.read(len(byte_view)).

**Comment by jonathanunderwood** [comment] 2019-05-10 18:55
Can you please format code sections and backtraces using backticks so they're actually readable. Please see the github markdown help.

**Comment by steve-talent** [comment] 2019-05-11 21:01
I edited the initial comment with markdown formatting.

**Comment by jonathanunderwood** [comment] 2019-05-11 21:02
Thank you, that makes it much more readable.

**Comment by jonathanunderwood** [comment] 2019-05-11 21:06
I am confused. You say that `TprofFile` uses `lz4.frame.LZ4FrameFile`, but the code you show doesn't at all. Instead it's using `lz4.frame.open()` directly.

Honestly, it's hard to help you without you showing the actual code, or, better, providing a simple reproducer. It would be worth your time reducing the part that is your only code to a simple reproducer, and then we can proceed.

**Comment by steve-talent** [comment] 2019-05-12 02:00
Results are the same when using either lz4.frame.LZ4FrameFile or lz4.frame.open() directly. Here is a simple test showing the failure.

#### Simple test using `lz4.frame.open()`: `test_lz4_read.py`
```python
import lz4.frame
import os

print( 'test compress then read of 8KB file' )
input_data = 8 * os.urandom( 1024 )
with lz4.frame.open( 'testfile_small', 'wb' ) as fp:
    bytes_written = fp.write( input_data )
    print( bytes_written )
    print( len( input_data ) )

with lz4.frame.open( 'testfile_small', 'rb' ) as fp:
    data = fp.read( 10 )
    print( len( data ) )

print( 'test compress then read of 9KB file' )
input_data = 9 * os.urandom( 1024 )
with lz4.frame.open( 'testfile_small', 'wb' ) as fp:
    bytes_written = fp.write( input_data )
    print( bytes_written )
    print( len( input_data ) )

with lz4.frame.open( 'testfile_small', 'rb' ) as fp:
    data = fp.read( 10 )
    print( len( data ) )
```
#### Console output
```
$ py test_lz4_read.py
test compress then read of 8KB file
8192
8192
10
test compress then read of 9KB file
9216
9216
Traceback (most recent call last):
  File "test_lz4_read.py", line 23, in <module>
    data = fp.read( 10 )
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\site-packages\lz4\frame\__init__.py", line 635, in read
    return self._buffer.read(size)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\_compression.py", line 69, in readinto
    byte_view[:len(data)] = data
ValueError: memoryview assignment: lvalue and rvalue have different structures
```
#### Simple test using `lz4.frame.LZ4FrameFile()`: `test_lz4_read_2.py`
```python
import lz4.frame
import os

print( 'test compress then read of 8KB file' )
input_data = 8 * os.urandom( 1024 )
with lz4.frame.LZ4FrameFile( 'testfile_small', 'wb' ) as fp:
    bytes_written = fp.write( input_data )
    print( bytes_written )
    print( len( input_data ) )

with lz4.frame.LZ4FrameFile( 'testfile_small', 'rb' ) as fp:
    data = fp.read( 10 )
    print( len( data ) )

print( 'test compress then read of 9KB file' )
input_data = 9 * os.urandom( 1024 )
with lz4.frame.LZ4FrameFile( 'testfile_small', 'wb' ) as fp:
    bytes_written = fp.write( input_data )
    print( bytes_written )
    print( len( input_data ) )

with lz4.frame.LZ4FrameFile( 'testfile_small', 'rb' ) as fp:
    data = fp.read( 10 )
    print( len( data ) )
```
#### Console output
```
$ py test_lz4_read_2.py
test compress then read of 8KB file
8192
8192
10
test compress then read of 9KB file
9216
9216
Traceback (most recent call last):
  File "test_lz4_read_2.py", line 23, in <module>
    data = fp.read( 10 )
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\site-packages\lz4\frame\__init__.py", line 635, in read
    return self._buffer.read(size)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\_compression.py", line 69, in readinto
    byte_view[:len(data)] = data
ValueError: memoryview assignment: lvalue and rvalue have different structures
```

**Comment by jonathanunderwood** [comment] 2019-05-12 09:36
That's great, thanks. I've now been able to reproduce this on the Appveyor builders for the `issue-172` branch. So, that's a start.

https://ci.appveyor.com/project/jonathanunderwood/python-lz4/builds/24481373/job/6i4r1cgcayfltckp

(Note that the first fail is for Python 2.7, which uses a bundled version of _compression.py, and the error message is different, but the underlying issue is the same).

**Comment by jonathanunderwood** [comment] 2019-05-12 09:38
Out of interest, does your test example succeed if instead you use bz2? (https://docs.python.org/3/library/bz2.html) - I'd try this, but I don't have access to windows (other than thru Appveyor builds).

**Comment by jonathanunderwood** [comment] 2019-05-12 14:19
Disappointingly, this seems to be unreproducible now:

https://travis-ci.org/python-lz4/python-lz4/builds/531422450

It definitely did occur once on Appveyor, but I haven't managed to get it to trigger again. Do you see it every time, or just intermittently?

**Comment by steve-talent** [comment] 2019-05-12 15:01
The test example succeeds when using bz2.
#### Test using bz2
```python
import bz2
import os

print( 'test compress then read of 8KB file' )
input_data = 8 * os.urandom( 1024 )
with bz2.open( 'testfile_8KB', 'wb' ) as fp:
    bytes_written = fp.write( input_data )
    print( bytes_written )
    print( len( input_data ) )

with bz2.open( 'testfile_8KB', 'rb' ) as fp:
    data = fp.read( 10 )
    print( len( data ) )

print( 'test compress then read of 9KB file' )
input_data = 9 * os.urandom( 1024 )
with bz2.BZ2File( 'testfile_9KB', 'wb' ) as fp:
    bytes_written = fp.write( input_data )
    print( bytes_written )
    print( len( input_data ) )

with bz2.BZ2File( 'testfile_9KB', 'rb' ) as fp:
    data = fp.read( 10 )
    print( len( data ) )
```
#### Console output
```
$ py test_bz2_read.py
test compress then read of 8KB file
8192
8192
10
test compress then read of 9KB file
9216
9216
10
```

**Comment by jonathanunderwood** [comment] 2019-05-12 15:03
Thanks.

Did you mean to close this issue?

**Comment by steve-talent** [comment] 2019-05-12 15:11
Hit wrong button.

**Comment by jonathanunderwood** [comment] 2019-05-12 15:14
Ok, just checking.

So, do you see this problem every time? Or intermittently?

**Comment by steve-talent** [comment] 2019-05-12 15:23
I see this problem every time the original source is larger than 8KB. As I mentioned in the edited initial comment, the call to ``` self._decompressor.decompress(rawblock, size)``` is returning 64KB for very large input files.

**Comment by jonathanunderwood** [comment] 2019-05-12 16:30
OK, I cannot get this to reproduce on Appveyor using your test case. See, eg:

https://travis-ci.org/python-lz4/python-lz4/builds/531453087

where I this test is being run: 

https://github.com/python-lz4/python-lz4/blob/issue-172/tests/frame/test_frame_9.py


Can you confirm:

(1) exactly which python lz4 package you're using
(2) whether you're using the lz4 library files, or a system lz4 library. If the latter, which version.
(3) does the problem still manifest if you start with a clean virtualenv and install the lz4 binaries using `pip install --no-binary lz4`.

At this point, I am thinking it's some sort of weird bug with the MSVC compiler that only manifests on some builds.

**Comment by steve-talent** [comment] 2019-05-12 17:15
1. Using this python lz4 package:
```
$ py -m pip show lz4
Name: lz4
Version: 2.1.6
Summary: LZ4 Bindings for Python
Home-page: https://github.com/python-lz4/python-lz4
Author: Jonathan Underwood
Author-email: jonathan.underwood@gmail.com
License: UNKNOWN
Location: c:\users\steve\appdata\local\programs\python\python36\lib\site-packages
Requires:
Required-by:
```
2. Not using system lz4

3.  Don't know how to use this option. After `py -m pip uninstall lz4`, I tried this:
```
$ py -m pip install --no-binary lz4
ERROR: You must give at least one requirement to install (see "pip help install")
```

Here is another test I just tried:

```python
import lz4.frame
import os

print( 'test compress then read of 9KB file' )
input_data = 9 * os.urandom( 1024 )
with lz4.frame.open( 'testfile_small', 'wb' ) as fp:
    bytes_written = fp.write( input_data )
    print( bytes_written )

print( 'get frame info' )
with open( 'testfile_small','rb') as fp:
    info = lz4.frame.get_frame_info( fp.read() )
    print(info)

print( 'call read( size = -1 )' )
with lz4.frame.open( 'testfile_small', 'rb' ) as fp:
    data = fp.read( size = -1 )
    print( 'len(data)', len( data ) )

print( 'call read( size = 16 * 1024 )' )
with lz4.frame.open( 'testfile_small', 'rb' ) as fp:
    data = fp.read( 16 * 1024 )
    print( 'len(data)', len( data ) )

print( 'call read( size = 16 * 1024 - 1 )' )
with lz4.frame.open( 'testfile_small', 'rb' ) as fp:
    data = fp.read( 16 * 1024 - 1 )
    print( 'len(data)', len( data ) )
```

```
$ py test_small.py
test compress then read of 9KB file
9216
get frame info
{'block_size': 65536, 'block_size_id': 4, 'block_linked': True, 'content_checksum': False, 'block_checksum': False, 'skippable': False, 'content_size': 0}
call read( size = -1 )
len(data) 9216
call read( size = 16 * 1024 )
len(data) 9216
call read( size = 16 * 1024 - 1 )
Traceback (most recent call last):
  File "test_small.py", line 27, in <module>
    data = fp.read( 16 * 1024 - 1 )
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\site-packages\lz4\frame\__init__.py", line 635, in read
    return self._buffer.read(size)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python36\lib\_compression.py", line 69, in readinto
    byte_view[:len(data)] = data
ValueError: memoryview assignment: lvalue and rvalue have different structures
```

**Comment by jonathanunderwood** [comment] 2019-05-12 17:24
Try `pip install lz4 --no-binary`

**Comment by steve-talent** [comment] 2019-05-12 17:28
That did not work.

**Comment by jonathanunderwood** [comment] 2019-05-12 17:32
I am on a train, so no access to a computer. How did it fail? Note that you will need a compiler installed, and the python development headers.

https://pip.pypa.io/en/stable/reference/pip_install/#install-no-binary

**Comment by steve-talent** [comment] 2019-05-12 18:16
```
steve@LAPTOP-B8R3RI9H MINGW64 ~/GitHub
$ py -m pip install --no-binary lz4
ERROR: You must give at least one requirement to install (see "pip help install")

steve@LAPTOP-B8R3RI9H MINGW64 ~/GitHub
$ py -m pip install --no-binary lz4 :all:
ERROR: Invalid requirement: ':all:'
```

**Comment by jonathanunderwood** [comment] 2019-05-12 18:44
Please re-read the command I specified above  - note the argument order.

**Comment by jonathanunderwood** [comment] 2019-05-12 19:30
OK, I seem to be relaibly reproducing this now on Appveyor. However, I won't have time to work on this again until next weekend, sadly.

**Comment by steve-talent** [comment] 2019-05-13 05:14
Thanks for working on the issue. I've downloaded Visual Studio Community edition with Python support, so I may be able to do more on this end. I just need to learn the build process.

**Comment by jonathanunderwood** [comment] 2019-06-01 14:04
OK, it looks like I have found the error here: it's the way that MSVC deals with comparisons of different types - it's a lot less forgiving than GCC. Just testing a fix now, but it's looking good.

**Comment by jonathanunderwood** [comment] 2019-06-01 16:34
Should be fixed in release 2.1.7 which should be available on PyPi in the next couple of hours.

**Comment by jonathanunderwood** [comment] 2019-06-01 16:35
Also: thanks for the report. Please re-open if you still see this problem.

**Closed by jonathanunderwood** 2019-06-01 16:34 UTC

**Comment by steve-talent** [comment] 2019-06-01 18:59
Thanks Jonathan, I just upgraded lz4 to version 2.1.7 from PyPi on my linux box for python versions 2.7.12, 3.5.2, and 3.7.3 and it looks good. I'll try it on on Windows a bit later.

Thank You!
